# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-

      - run:
          name: Install
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Test
          command: npm test

  dist:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-

      - run:
          name: Install
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Dist
          command: npm run dist

      - persist_to_workspace:
          root: .
          paths:
            - bin

  release:
    docker:
      - image: circleci/node:12.13
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(./bin/crabs-linux --version)
            ghr -t ${GITHUB_TOKEN} -n "Release ${VERSION}" -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/

workflows:
  version: 2
  test-dist-release:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - dist:
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
      - release:
          requires:
            - dist
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
