# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-

      - run:
          name: Install
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Test
          command: npm test

  dist:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-

      - run:
          name: Install
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Dist
          command: npm run dist

      - store_artifacts:
          path: bin

      - persist_to_workspace:
          root: .
          paths:
            - bin

  release:
    docker:
      - image: cibuilds/github:0.13

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: |
            cd bin
            ls
            cp crabs-linux crabs_linux
            ls
            chmod +x crabs_linux
            ./crabs_linux
            ./crabs-linux
            VERSION="v$(./crabs-linux --version)"
            echo "$VERSION"

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - dist:
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages

  release:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                -gh-pages
      - dist:
          filters:
            branches:
              ignore:
                -gh-pages
          requires:
            - test
      - release:
          filters:
            branches:
              ignore:
                -gh-pages
          requires:
            - dist
